const i18n = {
  sv: {
    "skip":"Hoppa till huvudinnehåll",
    "logo.sub":"ÄRENDEANALYS",
    "nav.problem":"När vi hjälper","nav.workflow":"Så fungerar det","nav.cases":"Kundärenden","nav.partners":"Samarbetspartner","nav.about":"Om Avertum","nav.contact":"Diskutera ett ärende",
    "hero.kicker":"ÄRENDEANALYS FÖR KOMPLEXA FINANSIELLA ÄRENDEN",
    "hero.title":"När pengar eller tillgångar har fastnat.<br><em>Vi driver ärendet framåt.</em>",
    "hero.lead":"Avertum strukturerar komplexa finansiella ärenden kring tvistiga transaktioner, illikvida investeringar, krav och återvinning till ett verifierat, beslutsfärdigt underlag.",
    "hero.thesis":"Ett akut ärende skapar ett verifierat underlag som senare kan återanvändas för nya krav, uppföljning och återkommande evidensarbete.",
    "hero.cta1":"Diskutera ett ärende →","hero.cta2":"Se hur det fungerar",
    "trust.1":"Komplexa finansiella ärenden","trust.2":"Varje faktum har en källa","trust.3":"Människor verifierar","trust.4":"Ärende → verifierat underlag → återanvändning",
    "problem.kicker":"DET KOMPLEXA FINANSIELLA ÄRENDET","problem.h2":"Dokumenten finns. Ingen äger helheten.",
    "problem.lead":"När en investering, betalning, tillgång eller ett krav blir tvistigt sitter kunden ofta med avtal, kontoutdrag, mejl, motparter och tidsfrister utspridda över banker, jurister, återvinningsaktörer och rådgivare.",
    "u1.k":"INVESTERINGAR & TILLGÅNGAR","u1.h":"Illikvida positioner","u1.1":"Onoterade aktier","u1.2":"Likvidation / ägarbild","u1.3":"Avyttring / möjlighet till realisering","u1.4":"Värdering / dokumentation",
    "u2.k":"BEDRÄGERI & ÅTERVINNING","u2.h":"Tvistiga investeringar","u2.1":"Handels- / kryptobedrägerier","u2.2":"Vilseledande uppgifter","u2.3":"Internationella motparter","u2.4":"Vägar till återvinning",
    "u3.k":"BANK & BETALNINGAR","u3.h":"Tvistiga transaktioner","u3.1":"Obehöriga överföringar","u3.2":"Försenat ingripande","u3.3":"Bankkorrespondens","u3.4":"Tidslinje & ansvar",
    "u4.k":"KRAV & TVISTER","u4.h":"Krav som måste drivas","u4.1":"Utebliven betalning","u4.2":"Avtalsbrott","u4.3":"Nekad ersättning","u4.4":"Tillgångstvister",
    "commercial.k":"DET KOMMERSIELLA TESTET","commercial.f":"Förväntad återvinning × sannolikhet − extern kostnad − Avertums avgift","commercial.p":"Varje ärende granskas utifrån grund, tidsfrist, motpart, möjlighet till återvinning och evidens. Avertum garanterar inte utfall.",
    "workflow.kicker":"ÄRENDE → VERIFIERAT UNDERLAG → ÅTERANVÄNDNING","workflow.h2":"Ett spårbart arbetsflöde från inlämning till överlämning till specialist.",
    "workflow.lead":"Avertum gör förarbetet: strukturerar verifierbar information, bygger tidslinje och evidensindex, synliggör luckor och samordnar nästa steg. Reglerade juridiska, insolvens- och finansiella åtgärder ligger hos behöriga specialister.",
    "f1.h":"LÄMNA IN","f1.p":"Lägg in transaktionen, investeringen, kravet och relevanta dokument.",
    "f2.h":"BEDÖM","f2.p":"Kontrollera grund, ägande, motparter, tidslinje, tidsfrister och evidensluckor.",
    "f3.h":"BYGG","f3.p":"Skapa verifierad ärendeakt, kronologi, evidensindex och förlustlogik.",
    "f4.h":"SAMORDNA","f4.p":"Styr ärendet till bank, försäkringsgivare, återvinningsaktör eller behörig specialist.",
    "f5.h":"DRIV VIDARE","f5.p":"Följ utfall, beslut, tidsfrister och åtgärder från samarbetspartner i ett gemensamt ärende.",
    "f6.h":"ÅTERANVÄND","f6.p":"Behåll det verifierade underlaget för nya krav, uppföljning och återkommande evidensarbete.",
    "cases.kicker":"AKTIVA KUNDÄRENDEN","cases.h2":"Tre aktiva kundärenden pekar mot samma kärnproblem.",
    "cases.lead":"Kundidentiteter och känsliga uppgifter visas inte. Mönstret är tydligt: pengar, tillgångar eller krav har fastnat och ingen part äger hela evidens- och samordningslagret.",
    "cases.signal":"3 aktiva kundärenden · samma återkommande behov av evidens, samordning och specialistöverlämning",
    "case.head1":"Ärendetyp","case.head2":"Utlösande händelse","case.head3":"Avertums roll",
    "c1.a":"Illikvida / onoterade innehav","c1.b":"Tvångslikvidation, ägarfrågor, svårrealiserade positioner","c1.c":"Ägar- och transaktionsbild, evidensstruktur, alternativ och specialistspår",
    "c2.a":"Investeringsbedrägeri & internationell återvinning","c2.b":"Handels- eller kryptobedrägeri, internationella motparter, illikvida innehav","c2.c":"Ärendeanalys, kravförberedelse, evidenspaket och specialistsamordning",
    "c3.a":"Bank- / betalningstvist","c3.b":"Obehöriga transaktioner och tvist om bankens agerande","c3.c":"Kronologi, bankkorrespondens, evidens och samordning med relevanta specialister",
    "partners.kicker":"DISTRIBUTION VIA SAMARBETSPARTNER","partners.h2":"När transaktionen är klar men problemet börjar.",
    "partners.lead":"Företagsfinansiering, juridik, insolvens, redovisning och försäkring ser ofta problemet först. Avertum kan ta det komplexa efterärendet utan att konkurrera om samarbetspartnerns kärnuppdrag.",
    "p1.h":"TRANSAKTION","p1.p":"Kapitalanskaffning · investering · ägande",
    "p2.h":"UTLÖSANDE HÄNDELSE","p2.p":"Illikviditet · likvidation · bedrägeri · tvistig betalning",
    "p3.h":"AVERTUM","p3.p":"Evidens · kronologi · motparts-/tillgångskarta · kravförberedelse",
    "p4.h":"SPECIALIST","p4.p":"Juridik · insolvens · återvinning · bank / försäkringsgivare",
    "partners.value":"Värde för samarbetspartner: behåll kundrelationen utan att bygga en intern krav- eller återvinningsfunktion.",
    "diff.kicker":"VAD SOM UTMÄRKER AVERTUM","diff.h2":"Generell artificiell intelligens skriver svar. Avertum bevarar beviskedjan.",
    "d1.h":"Källkoppling","d1.p":"Varje faktauppgift länkas till dokumentet eller dataposten den kommer från.",
    "d2.h":"Synliga luckor","d2.p":"Osäkerhet, motsägelser och saknade uppgifter döljs inte bakom ett välformulerat svar från artificiell intelligens.",
    "d3.h":"Mänsklig verifiering","d3.p":"Artificiell intelligens automatiserar förarbetet. Behöriga människor verifierar fakta och äger beslutet.",
    "d4.h":"Kontrollerad återanvändning","d4.p":"Samma verifierade underlag kan användas igen utan att beviskedjan bryts.",
    "about.kicker":"GRUNDARLEDD GENOMFÖRANDEKRAFT","about.h2":"Avertum byggs i skärningspunkten mellan komplexa finansiella ärenden, evidens och mänskligt ansvar.",
    "about.p":"15+ års erfarenhet av företagsförsäljning i reglerade branscher, finansiella tjänster och samhällskritisk infrastruktur. Historiska meriter presenteras separat från Avertums nuvarande kund- och produktvalidering.",
    "about.role":"GRUNDARE & VD","stat1.value":"15+ ÅR","stat1":"erfarenhet av företagsförsäljning i reglerade branscher","stat2":"fleråriga avtal vunna","stat3":"aktiva kundärenden",
    "contact.kicker":"KONFIDENTIELL FÖRSTA BEDÖMNING","contact.h2":"Starta med problemet — inte med känsliga detaljer.",
    "contact.p":"Beskriv kort vilken typ av situation det gäller. Om Avertum ser en rimlig väg framåt tar vi nästa steg under lämplig sekretess och med tydliga specialistgränser.",
    "contact.direct":"KONFIDENTIELL KONTAKT","form.name":"Namn","form.company":"Organisation","form.email":"E-post","form.situation":"Primärt behov",
    "opt0":"Välj typ av ärende...","opt1":"Investeringar / illikvida tillgångar","opt2":"Bedrägeri / återvinning","opt3":"Bank / betalningstvist","opt4":"Krav / kommersiell tvist","opt5":"Samarbetspartner / hänvisning",
    "form.message":"Kort beskrivning utan känsliga uppgifter","form.submit":"Diskutera ett ärende",
    "form.privacy":"När du skickar formuläret behandlar Avertum Group AB dina uppgifter för att hantera din förfrågan. Läs vår <button type=\"button\" class=\"privacy-inline\" style=\"background:none;border:0;color:var(--gold);text-decoration:underline;cursor:pointer\">integritetspolicy</button>.",
    "footer.legal":"<strong>Avertum Group AB</strong><br>Ärendeanalys & finansiell evidens<br>Sverige / EU<br><br>Avertum strukturerar verifierbar information och samordnar ärendeförberedelse och överlämning till specialist. Reglerade juridiska, insolvens- och finansiella åtgärder ligger hos behöriga specialister. Avertum ger inte juridisk rådgivning, fattar inte reglerade beslut och garanterar inte externa utfall.",
    "privacy.link":"Sekretess och integritet","cookie":"Cookieinställningar","privacy.h2":"Sekretess","privacy.p":"Dela inte känsliga uppgifter i första kontakten. Innan detaljer kring exponering, transaktioner eller motparter diskuteras kan sekretessavtal och lämplig säker kanal etableras."
  },
  en: {
    "skip":"Skip to main content",
    "logo.sub":"CASE INTELLIGENCE",
    "nav.problem":"Where we help","nav.workflow":"How it works","nav.cases":"Client cases","nav.partners":"Partners","nav.about":"About Avertum","nav.contact":"Discuss a case",
    "hero.kicker":"CASE INTELLIGENCE FOR COMPLEX FINANCIAL CASES",
    "hero.title":"When money or assets are stuck.<br><em>We move the case.</em>",
    "hero.lead":"Avertum structures complex financial cases involving disputed transactions, illiquid investments, claims and recovery into a verified, decision-ready record.",
    "hero.thesis":"An urgent case creates the verified record that can later support further claims, monitoring and recurring evidence workflows.",
    "hero.cta1":"Discuss a case →","hero.cta2":"See how it works",
    "trust.1":"Complex financial cases","trust.2":"Every fact has a source","trust.3":"Humans verify","trust.4":"Case → verified record → reuse",
    "problem.kicker":"THE COMPLEX FINANCIAL CASE","problem.h2":"The client has documents. No one owns the whole case.",
    "problem.lead":"When an investment, payment, asset or claim becomes disputed, the client is left coordinating contracts, statements, emails, counterparties and deadlines across banks, lawyers, recovery actors and advisers.",
    "u1.k":"INVESTMENTS & ASSETS","u1.h":"Illiquid positions","u1.1":"Unlisted shares","u1.2":"Liquidation / ownership","u1.3":"Exit / recoverability","u1.4":"Valuation / documentation",
    "u2.k":"FRAUD & RECOVERY","u2.h":"Disputed investments","u2.1":"Trading / crypto fraud","u2.2":"Misrepresentation","u2.3":"Cross-border parties","u2.4":"Recovery routes",
    "u3.k":"BANK & PAYMENTS","u3.h":"Disputed transactions","u3.1":"Unauthorised transfers","u3.2":"Delayed intervention","u3.3":"Bank correspondence","u3.4":"Timeline & accountability",
    "u4.k":"CLAIMS & DISPUTES","u4.h":"Claims that need to move","u4.1":"Non-payment","u4.2":"Contract breach","u4.3":"Denied cover","u4.4":"Asset disputes",
    "commercial.k":"THE COMMERCIAL TEST","commercial.f":"Expected recovery × probability − external cost − Avertum fee","commercial.p":"Every case is screened for basis, deadline, counterparty, recoverability and evidence. Avertum does not promise an outcome.",
    "workflow.kicker":"CASE → VERIFIED RECORD → REUSE","workflow.h2":"One traceable workflow from intake to specialist hand-off.",
    "workflow.lead":"Avertum prepares the case: structures verifiable information, builds the timeline and evidence index, exposes gaps and coordinates next steps. Regulated legal, insolvency and financial actions remain with authorised specialists.",
    "f1.h":"SUBMIT","f1.p":"Bring in the disputed transaction, investment, claim and supporting documents.",
    "f2.h":"ASSESS","f2.p":"Check basis, ownership, counterparties, timeline, deadlines and evidence gaps.",
    "f3.h":"BUILD","f3.p":"Create the verified case file, chronology, evidence index and loss logic.",
    "f4.h":"COORDINATE","f4.p":"Route the case to the bank, insurer, recovery actor or authorised specialist.",
    "f5.h":"MOVE FORWARD","f5.p":"Track outcomes, decisions, deadlines and partner actions in one case.",
    "f6.h":"REUSE","f6.p":"Retain the verified record for further claims, monitoring and recurring evidence workflows.",
    "cases.kicker":"ACTIVE CLIENT CASES","cases.h2":"Three active client cases point to the same core problem.",
    "cases.lead":"Client identities and sensitive details are omitted. The pattern is clear: money, assets or claims are stuck and no single actor owns the full evidence and coordination layer.",
    "cases.signal":"3 active client cases · recurring need for evidence, coordination and specialist hand-off",
    "case.head1":"Case type","case.head2":"Trigger","case.head3":"Avertum role",
    "c1.a":"Illiquid / unlisted holdings","c1.b":"Compulsory liquidation, ownership questions, hard-to-exit positions","c1.c":"Ownership and transaction picture, evidence structure, options and specialist routes",
    "c2.a":"Investment fraud & cross-border recovery","c2.b":"Trading/crypto scam, international counterparties, illiquid holdings","c2.c":"Case intelligence, claim preparation, evidence pack and specialist coordination",
    "c3.a":"Bank / payment dispute","c3.b":"Unauthorised transactions and dispute over bank response","c3.c":"Chronology, bank correspondence, evidence and coordination with relevant specialists",
    "partners.kicker":"PARTNER-LED DISTRIBUTION","partners.h2":"When the transaction is over but the problem begins.",
    "partners.lead":"Corporate finance, law, insolvency, accounting and insurance often see the trigger first. Avertum can take the complex after-case without competing for the partner's core mandate.",
    "p1.h":"TRANSACTION","p1.p":"Capital raise · investment · ownership","p2.h":"TRIGGER","p2.p":"Illiquidity · liquidation · fraud · disputed payment","p3.h":"AVERTUM","p3.p":"Evidence · chronology · counterparty/asset map · claim preparation","p4.h":"SPECIALIST","p4.p":"Legal · insolvency · recovery · bank / insurer",
    "partners.value":"Partner value: protect the client relationship without building an internal claims or recovery desk.",
    "diff.kicker":"WHAT MAKES AVERTUM DIFFERENT","diff.h2":"General AI writes answers. Avertum preserves the chain of evidence.",
    "d1.h":"Source linking","d1.p":"Every fact links to the document or data record it came from.","d2.h":"Visible gaps","d2.p":"Uncertainty, contradictions and missing information are not hidden behind a fluent AI answer.","d3.h":"Human verification","d3.p":"AI automates preparation. Authorised people verify facts and own the decision.","d4.h":"Controlled reuse","d4.p":"The same verified record can be reused without breaking the chain of evidence.",
    "about.kicker":"FOUNDER-LED EXECUTION","about.h2":"Building Avertum at the intersection of complex financial cases, evidence and human accountability.","about.p":"15+ years across regulated B2B, financial services and critical infrastructure. Historical founder achievements are presented separately from Avertum's current customer and product validation.","about.role":"FOUNDER & CEO","stat1.value":"15+ YEARS","stat1":"regulated B2B experience","stat2":"multi-year contracts won","stat3":"active client cases",
    "contact.kicker":"CONFIDENTIAL FIRST SCREEN","contact.h2":"Start with the problem — not sensitive details.","contact.p":"Briefly describe the type of situation. If Avertum sees a credible route forward, we take the next step under appropriate confidentiality and clear specialist boundaries.","contact.direct":"CONFIDENTIAL CONTACT",
    "form.name":"Name","form.company":"Organisation","form.email":"Email","form.situation":"Primary need","opt0":"Select case type...","opt1":"Investments / illiquid assets","opt2":"Fraud / recovery","opt3":"Bank / payment dispute","opt4":"Claims / commercial dispute","opt5":"Partner / referral","form.message":"Short description without sensitive data","form.submit":"Discuss a case",
    "form.privacy":"When you submit the form, Avertum Group AB processes your information to handle your enquiry. Read our <button type=\"button\" class=\"privacy-inline\" style=\"background:none;border:0;color:var(--gold);text-decoration:underline;cursor:pointer\">privacy policy</button>.",
    "footer.legal":"<strong>Avertum Group AB</strong><br>Case Intelligence & Financial Evidence<br>Sweden / EU<br><br>Avertum structures verifiable information and coordinates case preparation and specialist hand-off. Regulated legal, insolvency and financial actions remain with authorised specialists. Avertum does not provide legal advice, make regulated decisions or guarantee external outcomes.",
    "privacy.link":"Privacy & policy","cookie":"Cookie settings","privacy.h2":"Confidentiality","privacy.p":"Do not share sensitive information in the first contact. Before details about exposure, transactions or counterparties are discussed, an NDA and an appropriate secure channel can be established."
  }
};
const seo={sv:{title:'Avertum | Ärendeanalys för komplexa finansiella ärenden',description:'Avertum strukturerar komplexa finansiella ärenden kring investeringar, betalningar, krav och återvinning till verifierade, beslutsfärdiga underlag.',social:'När pengar eller tillgångar har fastnat. Vi driver ärendet framåt.',locale:'sv_SE',url:'https://avertum.se/'},en:{title:'Avertum | Case Intelligence for Complex Financial Cases',description:'Avertum structures complex financial cases involving investments, payments, claims and recovery into verified, decision-ready records.',social:'When money or assets are stuck. We move the case.',locale:'en_US',url:'https://avertum.se/?lang=en'}};
function applyLanguage(lang){const current=lang==='en'?'en':'sv';const dict=i18n[current];document.documentElement.lang=current==='en'?'en':'sv-SE';document.querySelectorAll('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;if(dict[k]!==undefined)el.textContent=dict[k];});document.querySelectorAll('[data-i18n-html]').forEach(el=>{const k=el.dataset.i18nHtml;if(dict[k]!==undefined)el.innerHTML=dict[k];});['sv','svm'].forEach(id=>document.getElementById(id)?.classList.toggle('active',current==='sv'));['en','enm'].forEach(id=>document.getElementById(id)?.classList.toggle('active',current==='en'));const meta=seo[current];document.title=meta.title;const setMeta=(sel,val)=>document.querySelector(sel)?.setAttribute('content',val);setMeta('meta[name="description"]',meta.description);setMeta('meta[property="og:title"]',meta.title);setMeta('meta[property="og:description"]',meta.social);setMeta('meta[property="og:locale"]',meta.locale);setMeta('meta[property="og:url"]',meta.url);setMeta('meta[name="twitter:title"]',meta.title);setMeta('meta[name="twitter:description"]',meta.social);document.querySelector('link[rel="canonical"]')?.setAttribute('href',meta.url);const url=new URL(window.location.href);current==='en'?url.searchParams.set('lang','en'):url.searchParams.delete('lang');history.replaceState({},'',url);}
function closeMenu(){const menu=document.getElementById('mobileMenu');const toggle=document.getElementById('menu-toggle');menu?.classList.remove('active');menu?.setAttribute('aria-hidden','true');toggle?.setAttribute('aria-expanded','false');document.body.classList.remove('menu-open');}
function toggleMenu(){const menu=document.getElementById('mobileMenu');const toggle=document.getElementById('menu-toggle');if(!menu)return;const open=!menu.classList.contains('active');menu.classList.toggle('active',open);menu.setAttribute('aria-hidden',String(!open));toggle?.setAttribute('aria-expanded',String(open));document.body.classList.toggle('menu-open',open);}
function openPrivacy(){document.getElementById('privacyModal')?.classList.add('active');document.body.classList.add('menu-open');}
function closePrivacy(){document.getElementById('privacyModal')?.classList.remove('active');document.body.classList.remove('menu-open');}
document.addEventListener('DOMContentLoaded',()=>{const y=document.getElementById('year');if(y)y.textContent=new Date().getFullYear();const initial=new URLSearchParams(location.search).get('lang')==='en'?'en':'sv';applyLanguage(initial);document.getElementById('sv')?.addEventListener('click',()=>applyLanguage('sv'));document.getElementById('svm')?.addEventListener('click',()=>{applyLanguage('sv');closeMenu();});document.getElementById('en')?.addEventListener('click',()=>applyLanguage('en'));document.getElementById('enm')?.addEventListener('click',()=>{applyLanguage('en');closeMenu();});document.getElementById('menu-toggle')?.addEventListener('click',toggleMenu);document.querySelectorAll('.mobile-link').forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('click',e=>{if(e.target.closest?.('.privacy-inline')){e.preventDefault();openPrivacy();}});document.getElementById('closeModal')?.addEventListener('click',closePrivacy);document.getElementById('privacyModal')?.addEventListener('click',e=>{if(e.target.id==='privacyModal')closePrivacy();});document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeMenu();closePrivacy();}});});